services:
  app:
    container_name: app-local
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: local-app:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env.local
    environment:
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    container_name: redis-local
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge