services:
  nginx:
    container_name: nginx-dev
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  app-blue:
    container_name: app-blue
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    ports:
      - "8081:8080"
      - "5005:5005"   # 원격 디버그 포트
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    env_file: .env.dev
    networks:
      - app-network
    volumes:
      - ./logs/blue:/app/logs
    depends_on:
      redis:
        condition: service_started

  app-green:
    container_name: app-green
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    ports:
      - "8082:8080"
      - "5006:5005"   # 원격 디버그용 포트
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    env_file: .env.dev
    networks:
      - app-network
    volumes:
      - ./logs/green:/app/logs
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
