spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.com.aigo.speech=INFO
logging.level.com.aigo.speech.global.AppStartupLogger=INFO
