# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.aigo.speech=DEBUG
# RDS 정보
DB_HOST=${PROD_DB_HOST}
DB_NAME=${PROD_DB_NAME}
DB_USERNAME=${PROD_DB_USERNAME}
DB_PASSWORD=${PROD_DB_PASSWORD}